support/chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('api/create-room/<str:uuid>/', views.create_room, name='create_room'),
    path('chat-admin/', views.admin, name='chat-admin'),
    path('chat-admin/room/<str:uuid>/', views.room, name='room'),
    path('chat-admin/room/<str:uuid>/delete/', views.delete_room, name='delete_room'),
]

support/support/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('', include('chat.urls')),
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

support/chat/models.py
from django.db import models

from accounts.models import User
# Create your models here.
class Message(models.Model):
    body = models.TextField()
    sent_by = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return self.sent_by
    

class Room(models.Model):
    WAITING = 'waiting'
    ACTIVE = 'active'
    CLOSED = 'closed'

    CHOICES_STATUS = (
        (WAITING, 'Waiting'),
        (ACTIVE, 'Active'),
        (CLOSED, 'Closed')
    )

    uuid = models.CharField(max_length=255)
    client = models.CharField(max_length=255)
    agent = models.ForeignKey(User, related_name='rooms', blank=True, null=True, on_delete=models.SET_NULL)
    messages = models.ManyToManyField(Message, blank=True)
    url = models.CharField(max_length=255, blank=True, null= True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=WAITING)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return f'{self.client} => {self.uuid}'

support/chat/views.py
import json
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Message, Room
from accounts.models import User

@require_POST
def create_room(request, uuid):
    name = request.POST.get('name', '')
    url = request.POST.get('url', '')

    Room.objects.create(uuid=uuid, client=name, url=url)

    return JsonResponse({'message': 'Room created'})


@login_required
def admin(request):
    rooms = Room.objects.all()
    users = User.objects.filter(is_staff=True)

    return render(request, 'chat/admin.html', {
        'rooms': rooms,
        'users': users
    })


@login_required
def room(request, uuid):
    room = Room.objects.get(uuid=uuid)

    if room.status == Room.WAITING:
        room.status = Room.ACTIVE
        room.agent = request.user
        room.save()

    return render(request, 'chat/room.html', {
        'room': room
    })


@login_required
def delete_room(request, uuid):

    if request.user.has_perm('room.delete_room'):
        room = Room.objects.get(uuid=uuid)
        room.delete()
        
        messages.success(request, 'The room was deleted!')
        return redirect('/chat-admin/')
    else:
        messages.error(request, 'You don\'t have permission to delete rooms!')
        return redirect('/chat-admin/')

support/chat/templates/chat/partials/chat_bubble.html
<div id='chat' class='max-w-[300px] fixed right-2 bottom-2 p-4 bg-white border border-rose-600 rounded-xl'>
    <div id='chat_icon'>
        <button id='chat_open' class='w-[40px] flex items-center'>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1" stroke="currentColor" class="text-rose-600">
                <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 8.511c.884.284 1.5 1.128 1.5 2.097v4.286c0 1.136-.847 2.1-1.98 2.193-.34.027-.68.052-1.02.072v3.091l-3-3c-1.354 0-2.694-.055-4.02-.163a2.115 2.115 0 01-.825-.242m9.345-8.334a2.126 2.126 0 00-.476-.095 48.64 48.64 0 00-8.048 0c-1.131.094-1.976 1.057-1.976 2.192v4.286c0 .837.46 1.58 1.155 1.951m9.345-8.334V6.637c0-1.621-1.152-3.026-2.76-3.235A48.455 48.455 0 0011.25 3c-2.115 0-4.198.137-6.24.402-1.608.209-2.76 1.614-2.76 3.235v6.226c0 1.621 1.152 3.026 2.76 3.235.577.075 1.157.14 1.74.194V21l4.155-4.155" />
            </svg>
        </button>
    </div>

    <div id='chat_welcome' class='hidden'>
        <button id='close' class='flex ml-auto justify-end mb-4'>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
        </button>
        <input type="text" name='name' id='chat_name' class='w-full mb-4 py-2 px-6 rounded-xl bg-gray-200' placeholder='Enter your name'>
        <button id='chat_join' class='py-2 px-6 rounded-xl text-white bg-rose-600'>Join chat</button>
    </div>

    <div id='chat_room' class='hidden'>
        <div id='chat_log' class='mb-4 p-4 bg-gray-200 rounded-xl h-[300px] overflow-auto'>
            <p>Welcome to our chat! Please type your message and wait for an agent to join...</p>
        </div>

        <input type='text' name='body' id='chat_input' class='w-full mb-4 p-4 bg-gray-200 rounded-xl' placeholder='Type your message...'>
        <button id='submit' class='py-2 px-6 rounded-xl text-white bg-rose-600'>Send</button>
    </div>
</div>

support/chat/templates/chat/partials/room_list.html
<div class='grid grid-cols-4 gap-4'>
    {% for room in rooms %}
    <div class='p-4 rounded-xl {% if room.status == 'waiting' %}bg-yellow-100 {% elif room.status == 'active' %}bg-emerald-200 {% else %}bg-gray-300{% endif %}'>
        <h3 class='mb-4 text-lg'><b>Chat</b></h3>

        <table>
            <tr><td class='p-2'><b>ID:     </b></td><td>{{room.uuid}}</td></tr>
            <tr><td class='p-2'><b>Name:   </b></td><td>{{room.client}}</td></tr>
            <tr><td class='p-2'><b>Status: </b></td><td>{{room.get_status_display}}</td></tr>
            <tr><td class='p-2'><b>Agent:  </b></td><td>{% firstof room.agent.name 'None yet...' %}</td></tr>
        </table>
        <div class='flex justify-between'>
            <a href="{% url 'chat:room' room.uuid %}" class='inline-block py-2 px-6 mt-4 bg-emerald-800 text-white rounded-xl'>Join</a>
            {% if perms.chat.delete_room %}
            <a href="{% url 'chat:delete_room' room.uuid %}" class='inline-block py-2 px-6 mt-4 bg-rose-800 text-white rounded-xl'>Delete</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>