support/accounts/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from .forms import LoginForm
from . import views

app_name = 'accounts'


urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html', form_class=LoginForm), name='login'),
    path('admin/add_user/', views.add_user, name='add_user'),
    path('admin/edit_user/<uuid:uuid>/', views.edit_user, name='edit_user'),
    path('admin/user_detail/<uuid:uuid>/', views.user_detail, name='user_detail'),
]

support/chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('api/create-room/<str:uuid>/', views.create_room, name='create_room'),
    path('chat-admin/', views.admin, name='chat-admin'),
    path('chat-admin/room/<str:uuid>/', views.room, name='room'),
    path('chat-admin/room/<str:uuid>/delete/', views.delete_room, name='delete_room'),
]

support/support/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('', include('chat.urls')),
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

support/accounts/models.py
import uuid

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.db import models
from django.utils import timezone


class CustomUserManager(UserManager):
    def _create_user(self, name, email, password, **extra_fields):
        if not email:
            raise ValueError("You have not provided a valid e-mail address")
        
        email = self.normalize_email(email)
        user = self.model(email=email, name=name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user
    
    def create_user(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(name, email, password, **extra_fields)
    
    def create_superuser(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(name, email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    AGENT = 'agent'
    MANAGER = 'manager'

    ROLES_CHOICES = (
        (AGENT, 'Agent'),
        (MANAGER, 'Manager'),
    )
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=255, blank=True, default='')
    role = models.CharField(max_length=20, choices=ROLES_CHOICES, default=AGENT)

    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

support/chat/models.py
from django.db import models

from accounts.models import User
# Create your models here.
class Message(models.Model):
    body = models.TextField()
    sent_by = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return self.sent_by
    

class Room(models.Model):
    WAITING = 'waiting'
    ACTIVE = 'active'
    CLOSED = 'closed'

    CHOICES_STATUS = (
        (WAITING, 'Waiting'),
        (ACTIVE, 'Active'),
        (CLOSED, 'Closed')
    )

    uuid = models.CharField(max_length=255)
    client = models.CharField(max_length=255)
    agent = models.ForeignKey(User, related_name='rooms', blank=True, null=True, on_delete=models.SET_NULL)
    messages = models.ManyToManyField(Message, blank=True)
    url = models.CharField(max_length=255, blank=True, null= True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=WAITING)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return f'{self.client} => {self.uuid}'

support/chat/views.py
import json
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Message, Room
from accounts.models import User

@require_POST
def create_room(request, uuid):
    name = request.POST.get('name', '')
    url = request.POST.get('url', '')

    Room.objects.create(uuid=uuid, client=name, url=url)

    return JsonResponse({'message': 'Room created'})


@login_required
def admin(request):
    rooms = Room.objects.all()
    users = User.objects.filter(is_staff=True)

    return render(request, 'chat/admin.html', {
        'rooms': rooms,
        'users': users
    })


@login_required
def room(request, uuid):
    room = Room.objects.get(uuid=uuid)

    if room.status == Room.WAITING:
        room.status = Room.ACTIVE
        room.agent = request.user
        room.save()

    return render(request, 'chat/room.html', {
        'room': room
    })


@login_required
def delete_room(request, uuid):

    if request.user.has_perm('room.delete_room'):
        room = Room.objects.get(uuid=uuid)
        room.delete()
        
        messages.success(request, 'The room was deleted!')
        return redirect('/chat-admin/')
    else:
        messages.error(request, 'You don\'t have permission to delete rooms!')
        return redirect('/chat-admin/')

support/chat/templates/chat/admin.html
{% extends 'core/base.html' %}

{% block content %}
<h1 class='text-2xl'>Chat admin</h1>
{% if perms.accounts.add_user %}
    <div class='mt-8'>
        <h2 class='mb-4 text-lg'>Users</h2>

        <a href="{% url 'accounts:add_user' %}" class='inline-block py-2 px-6 bg-rose-600 text-white rounded-xl'>Add user</a>

        <div class='mt-6'>
            {% for user in users %}
            <div class='grid grid-cols-4 gap-4 py-2 {% cycle 'bg-gray-200' 'bg-gray-400' %}'>
                <a href="{% url 'accounts:user_detail' user.pk %}"><p class='px-2'>{{user.name}}</p></a>
                <p class='px-2'>{{user.email}}</p>
                <p class='px-2'>{{user.get_role_display}}</p>
                <p class='px-2 text-right'>
                {% if perms.accounts.change_user %}
                    <a href="{% url 'accounts:edit_user' user.pk %}" class='underline'>Edit</a>
                {% endif %}
                </p>
            </div>
            {% endfor %}
        </div>
    </div>
{% endif %}

<hr class='my-6'>

<div class='mt-8'>
    <h2 class='mb-4 text-lg'>Rooms</h2>
    {% include 'chat/partials/room_list.html' %}
</div>

{% endblock %}

support/chat/templates/chat/room.html
{% extends 'core/base.html' %}

{% load static chatextras %}

{% block content %}
    <h1 class='text-2xl'><b>Room :</b> {{room.uuid}}</h1>

    <hr class='my-6'>

    <p class='mb-6'>
        <b>Name : </b>{{ room.client }} <br>
        <b>Started : </b>{{ room.created_at|timesince }} ago<br>
        <b>Status : </b>{{ room.get_status_display }} <br>
        <b>Page : </b>{{ room.url }} <br>
        <b>Agent : </b>{% firstof room.agent.name 'Not yet...' %} <br>
    </p>

    <hr class='my-6'>

    <div id='chat_log' class='mb-4 p-4 bg-gray-200 rounded-xl h-[300px] overflow-auto flex flex-col flex-grow'>
        {% for message in room.messages.all %}
        <div class='flex w-full max-w-md mt-2 space-x-3 {% if message.created_by %}ml-auto justify-end{% endif %}'>
            {% if not message.created_by %}
            <div class='flex-shrink-0 h-10 w-10 rounded-full bg-gray-300 text-center pt-2'>
                {{ message.sent_by|initials }}
            </div>
            {% endif %}

            <div>
                <div class='p-3 rounded-xl {% if message.created_by %}bg-blue-300{% else %}bg-gray-300{% endif %}'>
                    <p class='text-sm'>{{ message.body }}</p>
                </div>
                <span class='text-xs text-gray-500 leading-none'>{{ message.created_at|timesince }} ago</span>
            </div>

            {% if message.created_by %}
            <div class='flex-shrink-0 h-10 w-10 rounded-full bg-gray-300 text-center pt-2'>
                {{ message.sent_by|initials }}
            </div>
            {% endif %}
        </div>
        {% endfor %}
    </div>

    {% if room.status == 'active' %}
    <input type='text' name='body' id='chat_input' class='w-full mb-4 p-4 bg-gray-200 rounded-xl' placeholder='Type your message...'>
    <button id='submit' class='py-2 px-6 rounded-xl text-white bg-rose-600'>Send</button>
    {% endif %}
{% endblock content %}

{% block scripts %}
    {% if room.status == 'active' %}
    {{ room.uuid|json_script:'room_uuid' }}
    {{ request.user.name|json_script:'user_name' }}
    {{ request.user.id|json_script:'user_id' }}
    <script src="{% static 'js/main_admin.js' %}"></script>
    {% endif %}
{% endblock scripts %}